offline_memberships/views.py
import hashlib
import json
import operator
import uuid

import psycopg2
from flask import Blueprint, request, session, render_template, flash, url_for
from flask_login import current_user, logout_user
from psycopg2.extras import RealDictCursor
from werkzeug.exceptions import abort
from werkzeug.utils import redirect
import config
from appholder import csrf
from dbmodels import OfflineMemberships
from main import sendmailmandrill,sendbulkemails,verifyOtp,find_placeholders
from utilities.classes import Assembly_constituencies_details, encrypt_decrypt,Membership_details,Voter_details
from utilities.decorators import crossdomain,admin_login_required, janasainyam_login_required, required_roles
from utilities.general import checkUserAuth
from utilities.sms import sendBULKSMS,sendBULKSMS_samemessage
from celery_tasks.sms_email import send_bulk_email_operations,send_bulk_sms_excel,send_bulk_sms_operations,send_bulk_sms_manual
from utilities.mailers import genOtp
blueprint_offline_memberships = Blueprint('offline_memberships', __name__)
from utilities.others import generate_membershipid, makeResponse
from flasgger import swag_from

@blueprint_offline_memberships.route("/",methods=["GET","POST"])
@crossdomain(origin="*", headers="Content-Type")
def index():
    # from urlparse import urlparse
    # hostname=urlparse(request.url).hostname
    # districts={}
   
    # if hostname not in ['127.0.0.1','localhost']:
    #     subdomain = urlparse(request.url).hostname.split('.')[0]

    #     if subdomain is not None:
    #         districts=['srikakulam','viziangaram','visakhapatnam','eastgodavari','westgodavari','krishna','guntur','prakasam','nellore','anatapur','kadapa','kurnool','chittoor']
    #         if lower(subdomain) in districts:
    #             try:
    #                 districts['guntur']={'district_name':"Guntur","small_images":
    #                 ["/static/districts/hero-image-01-xs.jpg","/static/districts/hero-image-06-xs.jpg","/static/districts/hero-image-11-xs.jpg"],"medium_images":["/static/districts/hero-image-01.jpg","/static/districts/hero-image-06.jpg","/static/districts/hero-image-11_tel.jpg"]}
    #                 data=districts[lower(subdomain)]
                    
    #                 return render_template('districts/index.html',data=districts['guntur'])
    #             except Exception as e:
    #                 print str(e)
   
    return render_template('JSWebiste/index.html')


@blueprint_offline_memberships.route("/janasainyamLogin",methods=["GET","POST"])
@swag_from("swaggers/janasainyam_login_get.yml",methods=['GET'])
@swag_from("swaggers/janasainyam_login_post.yml",methods=['POST'])
def janasainyamLogin():
    
    if request.method == "POST":
        uname = request.form.get('username')
        password = request.form.get('password')
        utype = 'J'
        
        if checkUserAuth(uname, password, utype):
            
            session['next'] = url_for('offline_memberships.offlineMemberships')
            session['current'] = url_for('offline_memberships.janasainyamLogin')
            session['logged_in'] = True
            
            
            return redirect(url_for('.offlineMemberships'))
        else:
            
            flash('Invalid Details', 'error')
            return redirect(url_for('.janasainyamLogin'))
    else:
        if session.get('logged_in') is not None:
            if session.get('logged_in') == True and session.get('t')=='J':
                
                return redirect(url_for('.offlineMemberships'))
               
        
        return render_template("offline_memberships/login.html")


@blueprint_offline_memberships.route('/forgotJanasainyampass', methods=['GET', 'POST'])
@crossdomain(origin="*", headers="Content-Type")
@swag_from("swaggers/janasainyam_forgot_password_get.yml",methods=['GET'])
@swag_from("swaggers/janasainyam_forgot_password_post.yml",methods=['POST'])
def forgotJanasainyampass():
    if request.method == "POST":

        email = request.form.get("email")
        
        try:

            registered_user = OfflineMemberships.query.filter_by(email=email.lower()).first()
            
            if registered_user is not None:

                

                uuid_str = str(uuid.uuid4())
                con = psycopg2.connect(config.DB_CONNECTION)
                cur = con.cursor()
                cur.execute("update janasainyam_team set uuid=%s where lower(user_email)=%s",(uuid_str,str(email).lower()))
                con.commit()
                con.close()

                if (config.ENVIRONMENT_VARIABLE != 'local'):
                    resetlink = "<html>Hi, <br/><br/> Please click on the link below to reset your password:<a href=\'https://janasainyam.janasenaparty.org/resetJanasainyampassword?check=" + uuid_str + "&check=" + email + "\'>Click here to Reset Password</a></html>"
                else:
                    resetlink = "<html>Hi, <br/><br/> Please click on the link below to reset your password:<a href=\'http://127.0.0.1:5000/resetJanasainyampassword?check=" + uuid_str + "&check=" + email + "\'>Click here to Reset Password</a></html>"

                subject = "JanaSena Party Password Reset Link"
                msgToSendEmail = resetlink
                name = "JanaSena Party"
                sendmailmandrill(name, email, resetlink, subject)

                flash("Password Reset Link was sent successfully", 'success')
                return render_template("offline_memberships/forgotpassword.html")
            else:
                flash("Email Not Found", 'error')
                return render_template("offline_memberships/forgotpassword.html")

        except (psycopg2.Warning, psycopg2.Error) as e:
            print str(e)
            return json.dumps({'status': 'exception occured'})
    else:
        return render_template("offline_memberships/forgotpassword.html")

@blueprint_offline_memberships.route('/resetJanasainyampassword', methods=['GET', 'POST', 'OPTIONS'])
@crossdomain(origin="*", headers="Content-Type")

def resetJanasainyampassword():
    if request.method == 'GET':
        urldata = request.values.getlist('check')

        janasainyam_uuid = urldata[0]
        janasainyam_email = str(urldata[1])
        try:
            con = psycopg2.connect(config.DB_CONNECTION)
            cur = con.cursor()
            cur.execute("select user_email from janasainyam_team where uuid=%s",(janasainyam_uuid,))
            existing=cur.fetchone()
            if existing is not None:
                return render_template("offline_memberships/resetpassword.html")
            else:
                return "It Seems Given Link Expired.please request New one"

        except (psycopg2.Warning, psycopg2.Error) as e:
            return json.dumps({'error': 'exception occured'})

    elif request.method == 'POST':

        urldata = request.values.getlist('check')

        admin_uuid = urldata[0]
        admin_email = str(urldata[1])
        newpassword = request.form.get("newpass")
        print admin_uuid, admin_email, newpassword

        try:
            con = psycopg2.connect(config.DB_CONNECTION)
            cur = con.cursor()
            cur.execute("select user_email from janasainyam_team where uuid=%s",(admin_uuid,))
            existing=cur.fetchone()
            if existing is not None:
                unique = 'tomatoPotatoadmin'
                hashed_password = hashlib.sha256(newpassword + unique).hexdigest()
                cur.execute("update janasainyam_team set user_mod_hash=%s,update_dttm=now() where uuid=%s",(hashed_password,admin_uuid))
                con.commit()
                flash("Changed password Successfully", "success")
                return redirect(url_for("offline_memberships.janasainyamLogin"))
            else:
                flash("incorrect Details provided", "error")
                return redirect(url_for("offline_memberships.resetJanasainyampassword"))
            
            
        except (psycopg2.Warning, psycopg2.Error) as e:
            print str(e)
            return json.dumps({'status': 'exception occured'})

@blueprint_offline_memberships.route('/changePasswordjanasainyam', methods=['POST', 'GET'])
@crossdomain(origin="*", headers="Content-Type")
@janasainyam_login_required

def changePasswordjanasainyam():
    if request.method == 'POST':

        oldpass = request.values.get('oldpass')
        newpass = request.values.get('newpass')

        if oldpass is None or oldpass == "":
            return json.dumps({'errors': ['BAD_REQUEST', 'PARAMETER_oldpass_MISSING'], 'data': {'status': '0'}})
        if newpass is None or newpass == "":
            return json.dumps({'errors': ['BAD_REQUEST', 'PARAMETER_newpass_MISSING'], 'data': {'status': '0'}})

        try:
            print current_user
            admin_id = current_user.id
            print admin_id
            

            unique = 'tomatoPotatoadmin'

            old_hashed_password = hashlib.sha256(oldpass + unique).hexdigest()

            con = psycopg2.connect(config.DB_CONNECTION)
            cur = con.cursor()
            cur.execute('select user_mod_hash from janasainyam_team where id=%s', (admin_id,))
            password = cur.fetchone()[0]

            if str(password) == str(unicode(old_hashed_password, errors='ignore')):

                new_HashedPassword = hashlib.sha256(newpass + unique).hexdigest()
                cur.execute('update janasainyam_team  set user_mod_hash=%s,update_dttm=now() where id=%s',
                            (new_HashedPassword, admin_id,))

                con.commit()

                js = json.dumps({'errors': [], 'data': {'status': '1', 'msg': 'Password Changed successfully'}})

                return js

            else:
                js = json.dumps({'errors': ['old password does not match'], 'data': {'status': '0'}})

                return js



        except (psycopg2.Warning, psycopg2.Error) as e:
            print str(e)

templates/offline_memberships/callcenter.html
{% extends "janasainyam_layout.html" %}
 {% block head%}
<style>
.form-control 
{
	width:80% !important;
}
</style>
 <link rel="stylesheet" href="static/assets/css/sweetalert.css">
  <!-- <link rel="stylesheet" type="text/css" href="static/offline_memberships/css/mem.css"> -->
 <script type="text/javascript" src="static/assets/js/sweetalert.js"></script>
 {% endblock%}

{% block body %}
 <div  style="min-height:500px">
{% include 'loader.html' %}
	<div class="row" style="margin-top:30px;">
        		<h3  style="text-align:center;width:100%;color:rgba(28, 137, 255, 0.91);font-size:28px;font-weight:700">Call Center Form</h3>
        	</div>
		<form id="issues_form">
    
      <div class=" col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <label for="name" style="color:blue">Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Name"  required>
      </div>
      <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6">
        <label for="referral_id" style="color:blue">Voter ID</label>
        <input type="text" class="form-control" id="voter_id" name="voter_id" placeholder="Voter ID" >
      </div>
      <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6">
        <label for="receipt_no" style="color:blue">Age</label>
        <input type="text" class="form-control" id="age" placeholder="Enter Age" name="receipt_no" onkeypress="return isNumeric(event)" required>
      </div>
    

  <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6" >
    <label for="gender" style="color:blue">Gender</label>
    <select id="gender" name="gender" class="form-control" required>
      <option value="" selected>Select Gender</option>
      <option value="Male">Male</option>
      <option value="Female">Female</option>
      <option value="Transgender">Transgender</option>
    </select>
  </div>
  <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6" >
    <label for="state" style="color:blue">State</label>
    <select id="state" name="state" class="form-control" required>
      <option value="" selected>Select State</option>
      <option value="1">Andhra Pradesh</option>
      <option value="2">Telangana</option>
      <option value="3">Karnataka</option>
      <option value="4">Tamilnadu</option>
      <option value="5">Other</option>
    </select>
  </div>
  <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6">
    <label for="district" style="color:blue">Districts</label>
    <select id="district" name="district" class="form-control" required>
      <option selected value="">Select District</option>
    </select>
  </div>
  <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6">
    <label for="constituency" style="color:blue">constituency</label>
    <select id="constituency" name="constituency"class="form-control" required>
      <option selected value="">select Constituency</option>
    </select>
  </div>
    
      
      <div class=" col-md-6 col-xs-12 col-sm-6 col-lg-6">
       <input type="submit"  id="submit" class="btn btn-success" style="margin-top: 27px;
    width: 100px;" value="Submit">
        </div>
   

   
  </form>


 </div>       	
<script>
var districts = [];
  var ac;
var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
}; 
var load_districts_data= function load_districts_data()
{
	$.getJSON('static/offline_memberships/json/membership/districts.json', function (data) {
    districts = data;
   
    $.each(districts,function(i,dist){
      $.each(dist, function (j, val) {
        $('#district').append($("<option></option>").attr("value", val.id).text(val.district_name));
      });
    })
    console.log(districts)
  });
  $.getJSON('static/offline_memberships/json/membership/constituencies.json', function (data) {
    ac = data;
    
  });
 
} 

$(document).ready(function() {
  var phone=getUrlParameter('phone_number');
  console.log(window.location)
  history.pushState(window.location.href,null, "http://127.0.0.1:5000/call_center_form");
  load_districts_data();
  if(!phone)
  {
    swal("Info","phone number missing. please close and open the form again","info")
    return false;
  }

  

$('#state').change(function () {
  var state=$("#state").val();
  console.log(state)
  if(state>2)
  {
    $('#district').removeAttr("required");
    $('#constituency').removeAttr("required");
  }
  else
  {
    $('#district').attr("required","true");
    $('#constituency').attr("required","true");
  }
$('#district').html('');
$('#constituency').html('');
$('#district').append('<option value="" selected>Select District</option>')
var districts_data=districts[state];
 $.each(districts_data, function (i1, val1) {
      $('#district').append($("<option ></option>").attr("value", val1.id).text(val1.district_name));
    });
});
 
  $('#district').change(function () {

    var district_id = $(this).val();
    console.log(district_id)
    var local_ac = ac[district_id];

    $('#constituency').html('');
    $('#constituency').append('<option value="" selected>Select Constituency</option>')
    $.each(local_ac, function (i1, val1) {
      $('#constituency').append($("<option data-stateid='" + val1.state_id + "'></option>").attr("value", val1.constituency_id).text(val1.constituency_name));
    });
  })
  $('#issues_form').submit( function (e) {

			e.preventDefault();
 var data={};

  
  if(!phone)
  {
    swal("Info","phone number missing. please close and open the form again","info")
    return false;
  }
  $('.loader').css("display","block");
  data['phone']=phone;
  data['full_name']=$("#name").val();
  data['voter_id']=$("#voter_id").val();
  data['age'] = $("#age").val();
  data['gender'] =$("#gender").val();
  data['state_id'] =$("#state").val();
  data['constituency_id'] =$("#constituency").val();
  data['district_id'] =$("#district").val();
  
   
     $.ajax({
    type: "POST",
    url:  "/membership_with_callcenter",
    data: data,
    dataType: "json",
    
    success: function (response) {
      $('.loader').css("display","none");
       if(response.status=='1')
                    {
                            swal({
                            title: "Data Saved Successfully",
                            icon:"success",
                            text: "",
                            type: "success",
                            showCancelButton: false,
                            
                            confirmButtonText: "OK",
                            closeOnConfirm: false
                            },
                           function()
                           {
                            window.close();
                           });
                        }
                        else
                        {
                           $('.loader').css("display","none"); 
                        	swal({
                            title: response.errors[0],
                            icon:"info",
                            text: "",
                            type: "info",
                            showCancelButton: false,
                            
                            confirmButtonText: "OK",
                            closeOnConfirm: false
                            },
                           function()
                           {
                            window.close();
                           });

                        
                        
                        }

    },
    
                error:function(response)
                {
                swal("Error","please check your internet connection","error")
                $('.loader').css("display","none");
                }
  })
  })

 
})

function isNumeric (evt) {
    var theEvent = evt || window.event;
    var key = theEvent.keyCode || theEvent.which;
    key = String.fromCharCode (key);
    var regex = /[0-9\b]|\./;
    if ( !regex.test(key) ) {
      theEvent.returnValue = false;
      if(theEvent.preventDefault) theEvent.preventDefault();
    }
  } 
</script>

{% endblock%}

templates/offline_memberships/changepassword.html
{% extends "janasainyam_layout.html" %}
{% block head%}
{% endblock%}
{% block body %}
 
<div class="changepassword container">

    <div class="row" >
    <div class="col-xs-3 col-xs-offset-4">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3>Change Password</h3>
      </div>
      <div class="panel-body">
        <span style="color:red;">Password Must be 8 Characters Long</span>
        <input class="form-control" type="password" id='oldpass' placeholder="old password">
        <input class="form-control newp" type="password" id='newpass'  placeholder="new password">
        <input class="form-control confirmp" type="password"  id='confirmpass' placeholder="confirm password">
        <br>
        <span class='errormsg' style="Display:None; color:red;"> They Don't Match</span>
        <input class="btn btn-primary" id='cpsubmit' disabled type="submit">
        <button class="btn btn-info" id='cpcancel' >cancel</button>

      </div>

    </div>
    </div>
    </div>

</div>
<script>
$(document).ready(function(){


 var csrftoken = $('meta[name=csrf-token]').attr('content')

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
    }
});

 


$('.confirmp, .newp').keyup(function(){

    var newpass = $("#newpass").val();
    var confirmpass = $("#confirmpass").val();
    oldpass=$("#oldpass").val();
    if (oldpass.length>0  )
    {
    passOne = newpass;
    passTwo = confirmpass;
    
    checkAndChange();
    } 
     });

var checkAndChange = function()
  {
    
    if(passOne.length < 8){
      $('.errormsg').text('password must be 8 Characters Long');
       $('.errormsg').show();
      $('#cpsubmit').attr('disabled',true);
    }
    else
    {
          if(passOne == passTwo){
           $('.errormsg').hide();

          $('#cpsubmit').attr('disabled',false);


          }
          else
          {
            $('#cpsubmit').attr('disabled',true);
          $('.errormsg').text('They Dont match');
          $('.errormsg').show();
          }
}
      
  }

$('#cpsubmit').click(function()
{
  var oldpass=$('#oldpass').val();
  var newpass=$('#newpass').val();
  
  data={oldpass:oldpass,newpass:newpass}
 $.ajax({
                    url: "/changePasswordjanasainyam",
                    type: "POST",
                    data:data,
                    dataType: 'json',
                    success: function(result){ 
                     
                     
                        if(result.data.status=='1')
                            {
                               
                             alert('password changed Successfully');

                           
window.location.href="{{url_for('offline_memberships.janasainyamlogout')}}";

                }
                else{
                alert(result.errors);
                
                }
                }
                });  


});

})
</script>
{% endblock %}

templates/offline_memberships/create_janasainyam.html
{% extends "admin_layout.html" %}
{% block body %}
<style>


</style>
<div class="changepassword">

    <div class="row" >
    <div class="col-xs-6 col-md-6 col-sm-12 col-xs-offset-3">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3>Create  New USer</h3>
      </div>
      <div class="panel-body">
        <form id="frontdescform" name="frontdescform">
       
        <input class="form-control " type="text"  id='firstname' placeholder="First Name "  required><br>
         <input class="form-control " type="text"  id='lastname' placeholder="last name " required><br>
        <input class="form-control" type="email" id='email' placeholder="User Email" required><br>
        
        <input class="form-control " type="text" id='mobile'  placeholder="Mobile Number" required><br>
        <select name="district_id" id="district_id" class="form-control " required>
         
  
  <option value=""> Select District</option>
  
</select>
<br>
<select name="constituency_id" id="constituency_id" class="form-control " required>
  <option value=""> Select Constituency</option>
  </select> <br>     
       
        <input class="btn btn-primary form-control" id='submitfrontdesk'  type="submit">
       
</form>
      </div>

    </div>
    </div>
    </div>

</div>
<script>
var csrftoken = $('meta[name=csrf-token]').attr('content');
 $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
    }
})
$(document).ready(function(){

var districts=[];
var assembly_constituencies;
$.getJSON('/static/json/membership/districts.json',function(data){
   $.each(data, function (key,val) {
    if(parseInt(key)<=2)
    {
       $.each(val, function (index,value) {
      districts.push(value);
    });
    }
   
  });
 $('#district_id')
        .find('option')
        .remove()
        .end()
        .append('<option value="" selected>Select District</option>')
        .val('');
        $('#constituency_id')
        .find('option')
        .remove()
        .end()
        .append('<option value="" selected>Select Constituency</option>')
        .val('');
        $.each(districts, function (i,val) {
          $('#district_id').append($('<option>', { 
          value: val.id,
          text : val.district_name
          }));
          });

});
console.log(districts)
$.getJSON('/static/json/membership/constituencies.json',function(data){
  assembly_constituencies=data;

});



$("#district_id").change(function()
  {
  var district=$("#district_id").val();
 console.log(district)
  if (!district)
  {
    return false;
  };
 $.each(assembly_constituencies,function(i,val){
  if(district==i)
  {
    console.log(district)
    $('#constituency_id')
        .find('option')
        .remove()
        .end()
        .append('<option value="" selected>Select Constituency</option>')
        .val('');
        $.each(val, function (akey,avalue) {
         
          $('#constituency_id').append($('<option>', { 
          value: avalue.constituency_id,
          text : avalue.constituency_name
          }));
          });
  }

 });

 

});

$('#frontdescform').submit(function(e)
{
  e.preventDefault();
  
  
  var firstname=$("#firstname").val();
  var lastname=$("#lastname").val();
  var email=$("#email").val();
  var mobile=$("#mobile").val();
  var district_id=$("#district_id").val();
  var constituency_id=$("#constituency_id").val();
  data={uname:email,first_name:firstname,last_name:lastname,district_id:district_id,mobile:mobile,constituency_id:constituency_id}
 $.ajax({
                    url: "/createJanasainyamUser",
                    type: "POST",
                    data:data,
                    dataType: 'json',
                    success: function(result){ 
                     
                     
                        if(result.data.status=='1')
                            {
                               
                             alert('New User Created Successfully ');

                           
window.location.href="{{url_for('offline_memberships.getJanasainyamTeam')}}";

                }
                else{
                alert(result.errors);
                return false;
                
                }
                }
                });  


});

})
</script>
{% endblock %}

templates/offline_memberships/login.html
<html>
<head>
<meta charset='UTF-8'>
<meta name="robots" content="noindex">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='https://fonts.googleapis.com/css?family=Roboto:300,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="static/bootstrap.min.css">
<style>
    body{

background: #ffffff;
        
    }
.form-signin
{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
.form-signin .form-signin-heading, .form-signin .checkbox
{
    margin-bottom: 10px;
}
.form-signin .checkbox
{
    font-weight: normal;
}
.form-signin .form-control
{
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.form-signin .form-control:focus
{
    z-index: 2;
}
.form-signin input[type="text"]
{
    margin-bottom: -1px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.form-signin input[type="password"]
{
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.account-wall
{
    margin-top: 20px;
    padding: 40px 0px 20px 0px;
    background-color: #f7f7f7;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}
.login-title
{
    color: #555;
    font-size: 18px;
    font-weight: 400;
    display: block;
}
.profile-img
{
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}
.need-help
{
    margin-top: 10px;
}
.new-account
{
    display: block;
    margin-top: 10px;
}
</style>
    
</head>
<body>
    
    <div class="container">
    <div class="row">
        <div class="col-sm-12" style="margin-top: 50px">
            
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">

            <div class="account-wall">

                 <p style="text-align: center; margin-top: 50px; margin-bottom: 10px;"><img src="static/img/logo.png" width="100px" /></p>
                 {% with messages = get_flashed_messages() %}
                    {% if messages %}
                      <div class="alert alert-success">
                            <ul class="flashes">
                            {% for message in messages %}
                              <li style="color:red;">{{ message }}</li>
                            {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% endwith %}
                <form class="form-signin" method="post">
                 <h2 style="text-align:center">JanaSainyam Login!</h2>
                 <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="text" id='username' name='username' class="form-control" placeholder="Email" required autofocus>
                <input type="password" id='password' name='password' class="form-control" placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block" id="login" type="submit">
                    Go!</button>
                
                <a href="{{url_for('offline_memberships.forgotJanasainyampass')}}" class="pull-right need-help">Forgot Password? </a><span class="clearfix"></span>
                </form>


            </div>

        </div>
    </div>
</div>
    
    
</body>
    
</html>